SimpleData-Projekt/SimpleData/Kontrahenci/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from SimpleData.Kontrahenci.forms import kontrahenci_F  # import z innego pliku w tym samym miejscu musi zawierać . przed nazwą
from SimpleData import db, roles_required
from SimpleData.tabele import Kontrahenci
from sqlalchemy import text
from flask_login import login_required, current_user, fresh_login_required

kon = Blueprint('kon', __name__)

@kon.route('/kontrahenci', methods=['GET', 'POST'])
@login_required
def kontrahenci_t():
    form = kontrahenci_F()
    values=Kontrahenci.query.filter_by(stan="Aktywny")
    if request.method == 'POST':
        nip = request.form.get('nip')
        nazwa_firmy = request.form.get('nazwa_firmy')

        if nip and nazwa_firmy:
            kontrahenci = Kontrahenci.query.filter_by(NIP=nip, nazwa_firmy=nazwa_firmy, stan="Aktywny").all()
        elif nip:
            kontrahenci = Kontrahenci.query.filter_by(NIP=nip, stan="Aktywny").all()
        elif nazwa_firmy:
            kontrahenci = Kontrahenci.query.filter_by(nazwa_firmy=nazwa_firmy, stan="Aktywny").all()
        else:
            kontrahenci = Kontrahenci.query.filter_by(stan="Aktywny")

        return render_template('kontrahenci.html', kontrahenci=kontrahenci)


    return render_template('kontrahenci.html', kontrahenci=values, title="SimpleData", user=current_user.imie, form=form)

@kon.route('/dodaj_rekord', methods=['POST'])
@roles_required('Administrator')
def dodaj_rekord():
    nip = request.form.get('nip')
    nazwa_firmy = request.form.get('nazwa_firmy')
    miasto = request.form.get('miasto')
    nr_telefonu = request.form.get('nr_telefonu')
    ulica = request.form.get('ulica')
    numer = request.form.get('numer')
    rodzaj = request.form.get('rodzaj')
    stan = "Aktywny"
    kontrahent = Kontrahenci(NIP=nip, nazwa_firmy=nazwa_firmy, miasto=miasto, telefon=nr_telefonu, ulica=ulica, numer=numer, status=rodzaj, stan=stan)

    db.session.add(kontrahent)
    flash(f'Nowy kontrahent został utworzony.{nip}', 'success')
    db.session.commit()
    return redirect(url_for('kon.kontrahenci_t'))

@kon.route('/kontrahenci/edytuj', methods=['POST'])
@roles_required('Administrator')
def edytuj_kontrahenta():
    #Pobieranie danych z formularza
    edited_nip = request.form['editedField1']
    edited_nazwa_firmy = request.form['editedField2']
    edited_miasto = request.form['editedField3']
    edited_telefon = request.form['editedField4']
    edited_ulica = request.form['editedField5']
    edited_numer = request.form['editedField6']
    edited_rodzaj = request.form['editedField7']

   # Oznacz istniejący rekord jako "Nieaktualny"
    query1 = text("UPDATE kontrahenci SET stan=:stan_nieaktualny WHERE NIP=:nip AND stan=:stan_aktywny")
    db.session.execute(query1, {'stan_nieaktualny': 'Nieaktualny', 'nip': edited_nip, 'stan_aktywny': 'Aktywny'})
    db.session.commit()

    # Stwórz nowy rekord z aktualizowanymi wartościami i stanem "Aktywny"
    query2 = text("INSERT INTO kontrahenci (NIP, nazwa_firmy, miasto, telefon, ulica, numer, status, stan) VALUES (:nip, :nazwa_firmy, :miasto, :telefon, :ulica, :numer, :status, :stan_aktywny)")
    db.session.execute(query2, {'nip': edited_nip, 'nazwa_firmy': edited_nazwa_firmy, 'miasto': edited_miasto, 'telefon': edited_telefon, 'ulica': edited_ulica, 'numer': edited_numer, 'status': edited_rodzaj, 'stan_aktywny': 'Aktywny'})
    db.session.commit()

    flash('Dane kontrahenta zostały zaktualizowane')
    return redirect(url_for('kon.kontrahenci_t'))



@kon.route('/kontrahenci/<string:nip>', methods=['DELETE'])
@roles_required('Administrator')
def delete_kontrahent(nip):
    #Ustawianie obenego kontrahenta na stan nieakutalny
    kontrahent = Kontrahenci.query.filter_by(NIP=nip, stan="Aktywny").first()

    if kontrahent:
        kontrahent.stan = "Nieaktualny"
        db.session.commit()
        return jsonify({'message': 'Stan kontrahenta został zmieniony na Nieaktualny.'}), 200
    else:
        return jsonify({'message': 'Kontrahent o podanym NIP i stanie Aktywny nie został znaleziony.'}), 404

SimpleData-Projekt/SimpleData/Ogolne/views.py
from flask import Blueprint, jsonify, render_template, url_for, redirect
from datetime import datetime
from flask_login import current_user, login_required, logout_user
from SimpleData.Ogolne.forms import przeszukiwanie_d

ogolne = Blueprint('ogolne', __name__)

@ogolne.route('/api/time') # ustawiamy ścieżkę po jakiej będzie można się dostać do danej wartości/strony po wpisaniu w przeglądarkę
def current_time():
    now = datetime.now()  #pobieramy obecny czas z systemu
    formatted_now = now.strftime("%A, %d %B, %Y %H:%M") #ustalamy w jakim formacie będzie wyświetlany czas
    return jsonify({'time': formatted_now})

@ogolne.route('/')
@ogolne.route('/home') #Aby dana strona była dostępna pod dwoma ścieżkami wystarczy dodać pod sobą dwie linie kodu @app.route
def home():
    user = current_user.imie if current_user.is_authenticated else None
    return render_template( #używamy render_teamplate aby wygenerować stronę z danego pliku html, tworząc zmienne możemy je przekazać na stronę i następnie je tam wywołać
        "home.html",
        title = "SimpleData",    #taka zmienna którą możemy wyświetlić na stronie
        user=user
    )

@ogolne.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("ogolne.home"))

@ogolne.route('/przeszukiwanie', methods=['GET', 'POST'])
@login_required
def przeszukiwanie():
    form = przeszukiwanie_d()
    return render_template(
        "przeszukiwanie.html",
        title = "SimpleData",
        user = current_user.imie,
        form=form
    )

SimpleData-Projekt/SimpleData/Towary/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request, Flask
from SimpleData import app, db, roles_required
from SimpleData.Towary.forms import DodajDokumentForm, FiltrujDaneTowaryDostawcy, DodajDaneTowaryDostawcy  # import z innego pliku w tym samym miejscu musi zawierać . przed nazwą
from SimpleData.tabele import uzytkownicy, Kontrahenci, dokumenty, Towary
from sqlalchemy import inspect, text, delete
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import SQLAlchemyError
from flask_login import login_required, current_user, fresh_login_required

tow = Blueprint('tow', __name__)

@tow.route('/towary', methods=['GET', 'POST'])
@login_required
def towary():
    form=DodajDaneTowaryDostawcy()
    if form.validate_on_submit():
        if current_user.typ == 'Administrator' or current_user.typ == 'Kierownik':
            kontrahent = form.Firma.data
            query = "INSERT INTO towary (NIP, typ, rodzaj, nazwa, stan) VALUES (:nip, :typ, :rodzaj, :nazwa, 'Aktywna')"
            params = {'nip': kontrahent.NIP, 'typ': form.Typ.data, 'rodzaj': form.Rodzaj.data, 'nazwa': form.Nazwa.data}
            query = text(query)
            result = db.session.execute(query, params)
            db.session.commit()
            return redirect(url_for('tow.wypis_towary'))
        #wyrenderuj strone ze wzoru
    return render_template(
        "towary.html",
        title = "SimpleData",
        user = current_user.imie, #current_user - dane użytkownika, imie - krotka do której chcemy dostęp
        form=form
    )

@tow.route('/edytuj_towar/<towar_id>', methods=['GET', 'POST'])
@roles_required('Administrator')
def edytuj_towar(towar_id):
    form = FiltrujDaneTowaryDostawcy()
    rekord = Towary.query.filter_by(id_towaru=towar_id).first()
    form.NIP.data=rekord.NIP
    form.Typ.data=rekord.typ
    form.Rodzaj.data=rekord.rodzaj
    form.Nazwa.data=rekord.nazwa


    if form.validate_on_submit():
        if rekord:
            # Stwórz nowy rekord z aktualizowanymi wartościami i stanem "Aktywny"
            nowy_rekord = Towary(
                NIP=form.NIP.data,
                typ=form.Typ.data,
                rodzaj=form.Rodzaj.data,
                nazwa=form.Nazwa.data,
                stan="Aktywny"
            )
            db.session.add(nowy_rekord)
            db.session.commit()

            # Zmień stan istniejącego rekordu na "Nieaktualny"
            rekord.stan = "Nieaktualny"
            db.session.commit()

            flash('Dane zostały zaktualizowane.', 'success')
            return redirect(url_for('tow.wypis_towary'))
        else:
            flash('Rekord o podanym ID nie istnieje.', 'danger')
            return redirect(url_for('tow.wypis_towary'))
    return render_template( 
        "edytuj_towar.html",
        title = "SimpleData",
        user = current_user.imie, #current_user - dane użytkownika, imie - krotka do której chcemy dostęp
        #
        form=form,
    )

#usun towar z wiersza wybranego

@tow.route('/usun_towar/<towar_id>', methods=['GET', 'POST'])
@roles_required('Administrator')
@login_required
def usun_towar(towar_id):
    form = FiltrujDaneTowaryDostawcy()

    try:
        # Znajdź rekord towaru na podstawie towar_id
        rekord = Towary.query.filter_by(id_towaru=towar_id).first()

        if rekord:
            # Zmień stan rekordu na "Nieaktualny"
            rekord.stan = "Nieaktualny"
            db.session.commit()
            flash('Stan rekordu został zmieniony na "Nieaktualny".', 'success')
            return redirect(url_for('tow.wypis_towary'))
        else:
            flash('Nie znaleziono rekordu o podanym towar_id.', 'warning')

    except SQLAlchemyError as e:
        flash('Wystąpił błąd podczas zmiany stanu rekordu.', 'error')
        db.session.rollback()
    
    return render_template(
        "usun_towar.html",
        title="SimpleData",
        user=current_user.imie,
        form=form,
    )


@tow.route('/wypis-towary', methods=['GET', 'POST'])
@login_required
def wypis_towary():
    form = FiltrujDaneTowaryDostawcy()
    query = 'Select * from towary WHERE stan="Aktywna" '
    result = db.session.execute(text(query))
    if form.validate_on_submit():
        
        params = {}
        if form.NIP.data:
            query += 'AND NIP LIKE :NIP '
            params['NIP'] = form.NIP.data
        if form.Typ.data:
            query += 'AND Typ LIKE :Typ '
            params['Typ'] = form.Typ.data
        if form.Rodzaj.data:
            query += 'AND Rodzaj LIKE :Rodzaj '
            params['Rodzaj'] = form.Rodzaj.data
        if form.Nazwa.data:
            query += 'AND Nazwa LIKE :Nazwa '
            params['Nazwa'] = form.Nazwa.data
        query = text(query)
        result = db.session.execute(query, params)
        db.session.commit()
    # dodaj formularz form = kontrahenci()
    #wyrenderuj strone ze wzoru
    return render_template( 
        "wypis_towary.html",
        title = "SimpleData",
        user = current_user.imie, #current_user - dane użytkownika, imie - krotka do której chcemy dostęp
        form=form,
        values = result,
    )

SimpleData-Projekt/SimpleData/Uzytkownicy/views.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, flash, request
from SimpleData import db, bcrypt, roles_required
from SimpleData.Uzytkownicy.forms import RegistrationForm, LoginForm, Uzytkownicy, Users_zmiana, moje_ustawienia  # import z innego pliku w tym samym miejscu musi zawierać . przed nazwą
from SimpleData.tabele import uzytkownicy
from sqlalchemy import text
from flask_login import login_user, login_required, current_user
from flask_bcrypt import generate_password_hash, check_password_hash

users = Blueprint('users', __name__)

@users.route('/login',methods=['GET', 'POST'])    #oprócz ścieżki dodajemmy tu metody jakie mogą być obsługiwane na stronie, w tym momencie robimy to aby ta strona mogła onsługiwać formularze
def login():
    form = LoginForm()  #do zmiennej form przypisujemy model formularza który będzie działał na tej stronie
    if current_user.is_authenticated:
        return redirect(url_for('ogolne.home'))

    if form.validate_on_submit():   
            user = uzytkownicy.query.filter_by(email=form.email.data, stan="Aktywny").first()
            if user and bcrypt.check_password_hash(user.haslo, form.haslo.data):
                login_user(user)
                flash('Udało się zalogować', 'success')
                return redirect(url_for('ogolne.home'))
            else:
                flash('Logowanie nie udane. Sprawdź poprawność danych a wrazie dalszych problemów skontaktuj się z administratorem', 'danger')  #wiadomość jeśli dane będą nie poprawne
    return render_template(
        "login.html",
        title = "Logowanie",
        user = current_user.imie if current_user.is_authenticated else None,
        form=form #rendereujemy stronę i przekzaujemy formularz
        )
@users.route('/rejestruj', methods=['GET', 'POST'])
@roles_required('Administrator')
def rejestr():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.haslo.data).decode('utf-8')
        modyfikacja = uzytkownicy(imie=form.Nazwa.data, email=form.email.data, haslo=hashed_password, typ=form.typ_uzytkownika.data, stan="Aktywny") #przypisanie do zmiennej tabele z jej krotkami. Pobieramy dane do zmiany z formularza
        db.session.add(modyfikacja) #dodanie zmiennej modyfikacja do bazy
        db.session.commit() #wysłanie do bazy oraz zapisanie zmiany w niej
        flash(f'Konto stworzone! Zaloguj się.', 'success')
        return redirect(url_for('users.login'))
    return render_template('rejestr.html', 
        title='Rejestracja',
        user = current_user.imie if current_user.is_authenticated else None,
        form=form
        )

@users.route('/uzytkownicy', methods=['GET', 'POST'])
@login_required
def uzytkownicy_t():
    form = Uzytkownicy()
    form2 = Users_zmiana()
    values = uzytkownicy.query.filter_by(typ='').all()
    if form.validate_on_submit():
        values=uzytkownicy.query.all()
        query = 'SELECT * FROM uzytkownicy WHERE stan="Aktywny" '
        params = {}
        if form.imie.data:
            query += 'AND imie LIKE :imie '
            params['imie'] = form.imie.data
        if form.email.data:
            query += 'AND email LIKE :email '
            params['email'] = form.email.data
        if form.typ.data:
            query += 'AND typ LIKE :typ '
            params['typ'] = form.typ.data
        query = text(query)
        values = db.session.execute(query, params)
        db.session.commit()    
    return render_template(
            "uzytkownicy.html",
            title = "SimpleData",
            user = current_user.imie,
            form=form,
            form2=form2,
            values=values
        )

@users.route('/edit_user', methods=['GET', 'POST'])
@roles_required('Administrator')
def edit_user():
    user_id = request.form['id']
    user = uzytkownicy.query.filter_by(id=user_id).first()

    if user.imie != request.form['imie']:
        user.imie = request.form['imie']

    if user.haslo != request.form['haslo'] and request.form['haslo']:
        hashed_password = bcrypt.generate_password_hash(request.form['haslo']).decode('utf-8')
        user.haslo = hashed_password

    if user.email != request.form['email']:
        user.email = request.form['email']

    if user.typ != request.form['uprawnienia']:
        user.typ = request.form['uprawnienia']

    if db.session.dirty:
        db.session.commit()
        if current_user.id == int(user_id):
            flash(f'Zaktualizowano aktualnie zalogowanego użytkownika. Proszę zalogować się ponownie', 'success')
        return redirect(url_for('ogolne.logout'))
    else:
        flash('Nie zmieniono danych, nie zakutaliwano użytkownika')
        return redirect(url_for('users.uzytkownicy_t'))


@users.route('/uzytkownicy_us', methods=['GET', 'POST'])
@login_required
def ustawienia_kont():
    form = moje_ustawienia()

    if form.validate_on_submit():
        current_user.imie = form.username.data
        current_user.email = form.email.data

        # Sprawdzenie poprawności hasła przed zapisaniem zmian
        if form.password.data:
            if check_password_hash(current_user.haslo, form.password.data):
                # Hasło się zgadza, można zaktualizować
                new_password_hash = generate_password_hash(form.new_password.data)
                current_user.haslo = new_password_hash
            else:
                flash('Podano nieprawidłowe hasło.', 'error')
                return redirect(url_for('users.ustawienia_kont'))

        db.session.commit()
        flash('Twoje ustawienia zostały zaktualizowane.', 'success')
        return redirect(url_for('users.ustawienia_kont'))

    form.username.data = current_user.imie
    form.email.data = current_user.email

    return render_template('ustawienia_kont.html', form=form, imie=current_user.imie, email=current_user.email)

@users.route('/uzytkownicy/<int:ide>', methods=['DELETE'])
@roles_required('Administrator')
def delete_user(ide):
    if ide == 1:
        message = {'message': 'Tego użytkownika nie można usunąć.'}
        status_code = 200
    else:
        user = uzytkownicy.query.filter_by(id=ide).first()
        if user:
            user.stan = 'Usuniete'  # Zmiana wartości w kolumnie 'stan' na 'Usuniete'
            db.session.commit()
            message = {'message': 'Użytkownik został usunięty.'}
            status_code = 200
        else:
            message = {'message': 'Użytkownik o podanym id nie został znaleziony.'}
            status_code = 404
    return jsonify(message), status_code

SimpleData-Projekt/SimpleData/templates/home.html
{% extends "layout.html" %} <!-- pobiearamy szkielet strony  -->
{% block content %}

<div class="col-md-6" style="margin:auto">
    <div class="text-center">
        <h2>SimpleData</h2>

        <p>
            SimpleData
            Aplikacja ta służy do zarządzania magazynem. System wyświetla podgląd aktualnego
            stanu magazynu, umożliwa przepływ towarów, przyjmowanie na magazyn oraz ich wydawanie. Również podsumowuje towary które opuścił magaznym. System odpowiada za lokowanie
            towarów na magazynie.
        </p>
    </div>
</div>

{% endblock content %}

SimpleData-Projekt/SimpleData/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <meta charset="utf-8" />
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="/static/site.css" />
</head>

<body>
    <div class="container-fluid mb-4 " style="max-width: 760px; ">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} shadow rounded-lg rounded-8 mx-auto alert-dismissible fade show text-center" style="padding: 20px 50px; position: fixed; top: 15px; left: 50%; transform: translateX(-50%); z-index: 9999;" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light container-fluid">
        <a class="navbar-brand" href="/">SimpleData</a>

        <div class="collapse navbar-collapse flex-row-reverse container-fluid" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto pd-2">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Rozwiń
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if current_user.is_authenticated %}
                        {% if current_user.is_authenticated and current_user.uprawnienia == 'Administrator' %}
                        <a class="dropdown-item" href="{{ url_for('users.rejestr') }}">Rejestracja</a>
                        {% endif %}
                        <a class="dropdown-item" href="{{url_for('ogolne.przeszukiwanie')}}">Podsumowanie <span class="sr-only">(current)</span></a>
                        <a class="dropdown-item" href="{{url_for('kon.kontrahenci_t')}}">kontrahenci <span class="sr-only">(current)</span></a>
                        <a class="dropdown-item" href="{{url_for('mag.magazyn_towar_t')}}">Magazyn <span class="sr-only">(current)</span></a>
                        <a class="dropdown-item" href="{{url_for('users.uzytkownicy_t')}}">Użytkownicy <span class="sr-only">(current)</span></a>
                        <a class="dropdown-item" href="{{url_for('dok.dokumenty')}}">Dokumenty<span class="sr-only">(current)</span></a>
                        <a class="dropdown-item" href="{{url_for('tow.wypis_towary')}}">Dodaj/zobacz towary kontrahenta <span class="sr-only">(current)</span></a>

                        {% else %}
                        <a class="dropdown-item" href="{{ url_for('users.login') }}">Logowanie</a>
                        {% endif %}

                        <div class="dropdown-divider"></div>
                        {% if current_user.is_authenticated %}
                        <a class="dropdown-item" href="{{url_for('users.ustawienia_kont')}}">Ustawienia <span class="sr-only">(current)</span></a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('ogolne.home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if current_user.is_authenticated %}

                    <li class="nav-item active">
                        <a class="nav-link" href="">{{current_user.imie}} <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('ogolne.logout')}}">Wyloguj <span class="sr-only">(current)</span></a>
                    </li>

                {% endif %}

            </ul>
        </div>
    </nav>
    <div class="body-content">
        <div class="container">

            {% block content %}
            {% endblock %}

        </div>
        <footer>
            <p>&copy; 2023</p>
            <p id="time"></p>
            <script>
                (function ($) {
                    function nowa() {
                        $.getJSON('/api/time', function (data) {
                            $('#time').text(data.time);
                        });
                    }
                    nowa();
                    setInterval(nowa, 60000);
                })(jQuery);
            </script>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <!--window.addEventListener('beforeunload', function (e) {
    e.preventDefault();
    e.returnValue = '';
    logout();
    });

    function logout() {
    fetch('/logout', { method: 'POST' })
    .then(response => {
    if (response.ok) {
    // jeśli wylogowanie zakończyło się sukcesem, przekieruj użytkownika na stronę logowania
    window.location.href = '/login';
    } else {
    // w przeciwnym wypadku wyświetl błąd
    alert('Błąd wylogowania');
    }
    })
    .catch(error => console.error(error));
    }-->

</body>
</html>

SimpleData-Projekt/SimpleData/templates/przeszukiwanie.html
{% extends "layout.html" %}
{%block content%}
<div class="text-center">
    <p>W tym miejscu miało znaleźć się podsumowanie i spis towarów wprowadzonych oraz sprzedanych</p>
</div>

{%endblock%}

SimpleData-Projekt/SimpleData/templates/towar.html
{% extends "layout.html" %} <!-- pobiearamy szkielet strony  -->
{% block content %}

<div class="col-md-6" style="margin:auto">
    <div class="text-center">
        <h2>SimpleData</h2>
        <p>
           Dodaj dany towar do dostawcy. {{user}}
        </p>

        <form method="POST" action="">

            NIP<br />
            <input type="text" name="NIP"><br />
            Typ wody<br />
            <input type="text" name="typ wody"><br />
            Rodzaj butelki<br />
            <input type="text" name="typ butelki"><br />
            Nazwa wody wraz z pojemnoscią <br />
            <input type="text" name="nazwa wody"><br /><br />
            <a href="rejestr.html">
            <input type="button" value="dodaj produkt do wybranego dostawcy"></a><br />
        </form>
    </div>
</div>

{% endblock content %}

SimpleData-Projekt/SimpleData/templates/wypis_towary.html
{% extends "layout.html" %}
{%block content%}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-inline">
                <div class="form-group mr-3 mb-2 d-block">
                    <div class="d-block text-center">
                        <label for="{{ form.NIP.id }}" class="form-control-label">{{ form.NIP.label }}</label>
                    </div>
                    {{ form.NIP(class="form-control ml-2") }}
                </div>
                {% for field, errors in form.errors.items() %}
                <div class="alert alert-danger">
                    {% for error in errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group mr-3 mb-2 d-block">
                    <div class="d-block text-center">
                        <label for="{{ form.Typ.id }}" class="form-control-label">{{ form.Typ.label }}</label>
                    </div>
                    {{ form.Typ(class="form-control ml-2") }}
                </div>
                <div class="form-group mr-3 mb-2 d-block">
                    <div class="d-block text-center">
                        <label for="{{ form.Rodzaj.id }}" class="form-control-label">{{ form.Rodzaj.label }}</label>
                    </div>
                    {{ form.Rodzaj(class="form-control ml-2") }}
                </div>
                <div class="form-group mr-3 mb-2 d-block">
                    <div class="d-block text-center">
                        <label for="{{ form.Nazwa.id }}" class="form-control-label">{{ form.Nazwa.label }}</label>
                    </div>
                    {{ form.Nazwa(class="form-control ml-2") }}
                </div>


            </div>
        </fieldset>

        <div class="form-group text-center">
            {{ form.submit(class="btn btn-outline-info") }}
            {% if current_user.typ == 'Administrator' %}
            <a href="{{ url_for('tow.towary') }}" class="btn btn-primary">Dodaj towar do dostawcy</a>
            {% endif %}
        </div>
    </form>

    <table class="table table-striped align-items-center">
        <thead>
            <tr>
                
                <th scope="col">NIP</th>
                <th scope="col">Typ wody</th>
                <th scope="col">Rodzaj butelki</th>
                <th scope="col">Nazwa wody wraz z pojemnością</th>
                
            </tr>
        </thead>
        <tbody>
                {% for item in values %}
            <tr class="table-info">
            <tr>

                <td>{{ item.NIP }}</td>
                <td>{{ item.typ }}</td>
                <td>{{ item.rodzaj }}</td>
                <td>{{ item.nazwa }}</td>
                {% if current_user.typ == 'Administrator' %}
                <td>
                    <a href="{{url_for("tow.edytuj_towar", towar_id=item.id_towaru)}}" class="btn btn-grey ">Edytuj</a>
                </td>

                <td>
                    <a href="{{url_for("tow.usun_towar", towar_id=item.id_towaru)}}" class="btn btn-grey ">Usuń</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
    {%endblock%}